---
- name: Clone the repository
  hosts: all
  become: true
  tags: [clone-repo]
  vars:
    REPO_DEST: /tmp/cluster-env

  tasks:
    - name: Install git
      ansible.builtin.apt:
        pkg: git
        update_cache: yes

    - name: Clone the repository
      ansible.builtin.git:
        repo: "https://github.com/CUHKSZ-HPC/cluster-env.git"
        dest: "{{ REPO_DEST }}"

- name: Install slurm-client
  hosts: compute
  become: true
  tags: [slurm]
  tasks:
    - name: Install slurm-client
      ansible.builtin.apt:
        pkg: slurm-client
        update_cache: yes

- name: Install Intel oneAPI HPC Toolkit
  hosts: all
  become: true
  tags: [intel-oneapi-hpc-toolkit]
  vars:
    REPO_DEST: /tmp/cluster-env
    ONEAPI_VERSION: 2025.0

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - gpg-agent
          - wget
          - cmake
          - pkg-config
          - build-essential
        update_cache: yes

    - name: Download keyring and add repository to system
      ansible.builtin.command:
        cmd: bash {{ REPO_DEST }}/scripts/oneapi/install.sh

    - name: Install package intel-oneapi-hpc-toolkit
      ansible.builtin.apt:
        pkg: intel-oneapi-hpc-toolkit
        update_cache: yes

    - name: Set ptrace scope to 0
      ansible.builtin.command:
        cmd: sudo sed -i 's/kernel.yama.ptrace_scope = 1/kernel.yama.ptrace_scope = 0/' /etc/sysctl.d/10-ptrace.conf

    - name: Clean sampling drivers
      ansible.builtin.command:
        cmd: sudo ./rmmod-sep -s
        chdir: /opt/intel/oneapi/vtune/{{ ONEAPI_VERSION }}/sepdk/src
    - name: Build sampling drivers
      ansible.builtin.command:
        cmd: sudo ./build-driver -ni -pu
        chdir: /opt/intel/oneapi/vtune/{{ ONEAPI_VERSION }}/sepdk/src
    - name: Install sampling drivers
      ansible.builtin.command:
        cmd: sudo ./boot-script --install -g vtune -pu
        chdir: /opt/intel/oneapi/vtune/{{ ONEAPI_VERSION }}/sepdk/src

    - name: Add VTune to /etc/profile.d/oneapi.sh
      ansible.builtin.command:
        cmd: bash {{ REPO_DEST }}/scripts/oneapi/add_to_profile.sh

- name: Install Telegraf
  hosts: all
  become: true
  tags: [install-telegraf]
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - telegraf
          - lm_sensors
        update_cache: yes

- name: Copy Slurm config file to common/tmp
  hosts: master
  become: true
  tags: [copy-slurm-config]
  vars:
    REPO_DEST: /tmp/cluster-env
  tasks:
    - ansible.builtin.command:
        cmd: bash {{ REPO_DEST }}/scripts/slurm/config/copy_to_common.sh

- name: Copy Slurm config file to etc/slurm
  hosts: compute
  become: true
  tags: [copy-slurm-config]
  vars:
    REPO_DEST: /tmp/cluster-env
  tasks:
    - ansible.builtin.command:
        cmd: bash {{ REPO_DEST }}/scripts/slurm/config/copy_to_etc.sh
